name: Robot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 克隆仓库
        run: git clone https://github.com/yi985432/BotQ

      - name: 运行
        run: |
          cd BotQ
          7z x QQbot.zip
          cd QQbot
          nohup sh start.sh &
          
